name: Build Arcus.Security CI

trigger:
- master

variables:
- group: 'Arcus Security - Integration Testing'
- group: 'Build Configuration'
- name: 'solution'
  value: 'src/*.sln'

stages:
  - stage: Build
    jobs:
    - job: Compile
      pool:
        vmImage: 'ubuntu-16.04'
      steps:
      - task: DotNetCoreCLI@2
        displayName: 'Compile'
        inputs:
          projects: '$(solution)'
          arguments: '--configuration $(Build.Configuration)'
  - stage: UnitTests
    dependsOn: Build
    jobs:
    - job: UnitTests
      pool:
        vmImage: 'ubuntu-16.04'
      steps:
      - task: DotNetCoreCLI@2
        displayName: 'Run unit tests'
        inputs:
          command: test
          projects: 'src/**/Arcus.Security.Tests.Unit.csproj'
          arguments: '--no-build --configuration $(Build.Configuration)'
  - stage: IntegrationTests
    dependsOn: Build
    jobs:
    - job: Run_integration_tests
      pool:
        vmImage: 'ubuntu-16.04'
      steps:
      - task: qetza.replacetokens.replacetokens-task.replacetokens@3
        displayName: 'Replace integration test tokens'
        inputs:
          rootDirectory: 'src/Arcus.Security.Tests.Integration/'
          targetFiles: 'appsettings.json'
          encoding: 'auto'
          writeBOM: true
          actionOnMissing: 'fail'
          keepToken: false
          tokenPrefix: '#{'
          tokenSuffix: '}#'
      - task: DotNetCoreCLI@2
        displayName: 'Run integration tests'
        inputs:
          command: test
          projects: 'src/**/Arcus.Security.Tests.Integration.csproj'
          arguments: '--no-build --configuration $(Build.Configuration)'


