name: Build Arcus.Security CI

trigger:
- master

variables:
- group: 'Arcus Security - Integration Testing'
- name: 'solution'
  value: 'src/**/*.sln'

stages:
  - stage: Build
    jobs:
    - job: Build
      pool:
        vmImage: 'ubuntu-16.04'
      steps:
      - task: DotNetCoreCLI@2
        displayName: 'Restore .NET Core'
        inputs:
          command: 'restore'
          projects: $(solution)
      - task: DotNetCoreCLI@2
        displayName: 'dotnet build'
        inputs:
          projects: '$(solution)'
          arguments: '--configuration $(Build.Configuration)'
