name: Build Arcus.Security CI

trigger:
- master

variables:
- group: 'Build Configuration'
- group: 'Arcus Security - Integration Testing'

stages:
  - stage: Build
    jobs:
    - job: Build
      pool:
        vmImage: 'ubuntu-16.04'
      steps:
      - task: DotNetCoreCLI@2
        displayName: 'Restore .NET Core'
        inputs:
          command: 'restore'
          projects: '$(Parameters.projects)'
      - task: DotNetCoreCLI@2
        displayName: 'dotnet build'
        inputs:
          projects: '$(Parameters.projects)'
          arguments: '--configuration $(Build.Configuration)'
