name: Build Arcus.Security CI

trigger:
- master

variables:
- group: 'Arcus Security - Integration Testing'
- group: 'Build Configuration'
- name: 'solution'
  value: 'src/*.sln'

stages:
  - stage: Build
    jobs:
    - job: Restore_and_Compile
      pool:
        vmImage: 'ubuntu-16.04'
      steps:
      - task: DotNetCoreCLI@2
        displayName: 'Restore .NET Core'
        inputs:
          command: 'restore'
          projects: $(solution)
      - task: DotNetCoreCLI@2
        displayName: 'Build .NET Core'
        inputs:
          projects: '$(solution)'
          arguments: '--configuration $(Build.Configuration)'
  - stage: UnitTests
    dependsOn: Build
    jobs:
    - job: UnitTests
      pool:
        vmImage: 'ubuntu-16.04'
      steps:
      - task: qetza.replacetokens.replacetokens-task.replacetokens@3
        inputs:
          rootDirectory: 'src/Arcus.Security.Tests.Integration/'
          targetFiles: 'appsettings.json'
          encoding: 'auto'
          writeBOM: true
          actionOnMissing: 'fail'
          keepToken: false
          tokenPrefix: '#{'
          tokenSuffix: '}#'
      - task: DotNetCoreCLI@2
        displayName: 'Run Unit Tests'
        inputs:
          command: test
          projects: 'src/**/Arcus.Security.Tests.Unit.csproj'
          arguments: '--configuration $(Build.Configuration)'

