repository: arcus-azure/arcus.security
theme: jekyll-theme-slate
logo: https://raw.githubusercontent.com/arcus-azure/arcus/master/media/arcus.png
title: Arcus Security
description: Azure Security development in a breeze
plugins:
  - jemoji
